name: Regression

on:
  pull_request:
    branches: ["main"]

jobs:
  regression:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        targets:
          - https://github.com/cli/cli.git
          - https://github.com/anchore/grype.git
          - https://github.com/gin-gonic/gin.git
          - https://github.com/reviewdog/reviewdog.git
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install
        run: go install -v .

      - name: Setup gorcerer
        run: go install -v github.com/seiyab/gorcerer@latest

      - name: Inspect
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gorcerer job "inspect ${{ matrix.target }}" --repository gost --issue "${{ github.event.pull_request.number }}"
